# Generated by Django 2.1.5 on 2019-01-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamenageriemanager', '0002_remove_equipment_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('LI', 'Litire'), ('FE', 'Mangeoire'), ('WH', 'Roue'), ('NE', 'Nid')], default='LI', max_length=2),
        ),
    ]
