# Generated by Django 2.1.5 on 2019-01-19 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lamenageriemanager', '0003_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='last_move_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 11, 41, 6, 638319, tzinfo=utc)),
        ),
    ]
