# Generated by Django 2.1.5 on 2019-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamenageriemanager', '0004_animal_last_move_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='last_move_date',
            field=models.DateTimeField(),
        ),
    ]
