# Generated by Django 2.1.5 on 2019-01-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamenageriemanager', '0005_auto_20190119_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
